### ISSUE TITLE
specifying URL query parameters in the jasmine_url option

### ISSUE THREAD

**Issue by kbullaughey** [guard/guard-jasmine#174]
I use jasminerice with guard-jasmine and the jasmine docs suggest that my specs will load much faster if I set debug=true in a query parameter: 

    http://localhost:3000/jasmine?debug=false

Wanting to do this when running the specs with guard-jasmine I tried adding the following options:

    port: 55998, jasmine_url: 'https://localhost:55998/jasmine?debug=false'

However, this didn't work because when running individual specs it ended up like this:

    https://localhost:55998/jasmine?debug=false?spec=SomeSpecs

And the whole set run. 

It would be helpful if `Guard::Jasmine::Runner.query_string_for_suite` checked for whether the url already contains any query parameters and begins the encoded_url with either `?` or `&` accordingly.

I resorted to the following hack, that I placed in the end of my Guardfile:

    module ::Guard::Jasmine::Runner
      class << self
        unless method_defined? :query_string_for_suite
          alias_method :orig_query_string_for_suite, :query_string_for_suite
        end
        def query_string_for_suite(*args)
          encoded_url = orig_query_string_for_suite *args
          if encoded_url =~ /^\?/
            encoded_url = encoded_url.sub /^\?/, "?debug=false&"
          else
            encoded_url = "?debug=false"
          end
          encoded_url
        end
      end
    end

Is there a less hacky way to accomplish this? Or does it require a change to guard-jasmine? I'm not familiar with the spectrum of typical configurations and runner combinations to know whether this is the right place for such a change.

Thanks!

**Comment by nathanstitt** [comment]
I'm pruning old issues I hope the new version worked for you, please open a new issue if you're still having problems

**Comment by kbullaughey** [comment]
Ah. No worries. I switched away from using Jasmine because QUnit was better supported for Ember at the time. Appologies for the dangling issue.
