### ISSUE TITLE
JRuby: Cannot start Rake task server: The system cannot find the file specified.

### ISSUE THREAD

**Issue by karlhe** [guard/guard-jasmine#175]
Following error when trying to start server:
```
Cannot start Rake task server: The system cannot find the file specified. (2)
```

Appears to be a problem with the command sent to ChildProcess. Modifying it to have a prefix of `jruby -S` appears to get it past this stage but it's hard to tell whether my setup is otherwise working properly.

```ruby
self.process = ChildProcess.build(*['jruby', '-S', 'rackup', '-E', environment.to_s, '-p', port.to_s, '-s', server.to_s, rackup_config].compact)
```

windows 7
jruby 1.7.11
rails 3.2.18
jasminerice 0.0.10
guard-jasmine 1.19.2
childprocess 0.5.5

**Comment by nathanstitt** [comment]
I'm pruning old issues I hope the new version worked for you, please open a new issue if you're still having problems
