### ISSUE TITLE
Error "Cannot decode JSON from PhantomJS runner" for phantomjs v1.9.8

### ISSUE THREAD

**Issue by fifigyuri** [guard/guard-jasmine#176]
Running the specs in the browser pass, but running guard-jasmine fails with "Cannot decode JSON from PhantomJS runner".

**Comment by nathanstitt** [comment]
@fifigyuri I've just merged #181 and am testing it now.  Assuming that goes well, I'll push out a 2.0.2 release shortly that should resolve this.

**Comment by nathanstitt** [comment]
ok, i've tested out #181 and appears to work excellently on my system.  I've also added some improved error reporting and have cut a 2.0.2 release.

Please give that a try and let me know how it works.

**Comment by sahin** [comment]
After bundle update,  rails 4.2 , phamtom 1.9.8 

I am getting the following error
Guard::Jasmine starts thin spec server on port 53718 in test environment (coverage off).
Waiting for Jasmine test runner at http://localhost:53718/jasmine
Run all Jasmine suites
Something went wrong: An error occurred in the Jasmine runner
Guard::Jasmine stops server.

**Comment by nathanstitt** [comment]
Hi sahin,

I doubt that the error you are receiving is related.   Would it be possible for you to share your Guardfile?

**Comment by sahin** [comment]
````

interactor :simple

#guard 'livereload', host: '//movielala.com', , apply_css_live: true, override_url: true, grace_period: 0.5 do
guard 'livereload', host: 'movielala.com', port: '35729' do
  watch(%r{app/views/.+\.(erb|haml|slim)$})
  watch(%r{app/helpers/.+\.rb})
  watch(%r{public/.+\.(css|js|html)})
  watch(%r{config/locales/.+\.yml})
  # Rails Assets Pipeline
  watch(%r{(app|vendor)(/assets/\w+/(.+\.(css|js|html))).*}) { |m| "/assets/#{m[3]}" }
end

#guard bundler is not for guard 2.0
guard 'bundler' do
  watch('Gemfile')
  # Uncomment next line if Gemfile contain `gemspec' command
  watch(/^.+\.gemspec/)
end

guard :cucumber, :all_on_start => false, :all_after_pass => false, :cli => '--profile guard -c', :bundler => false do
  watch(%r{^features/.+\.feature$})
  watch(%r{^features/support/.+$})          { 'features' }
  watch(%r{^features/step_definitions/(.+)_steps\.rb$}) { |m| Dir[File.join("**/#{m[1]}.feature")][0] || 'features' }
end

guard :rspec, all_on_start: false, failed_mode: :focus  do
  watch('spec/spec_helper.rb')                        { "spec" }
  watch('config/routes.rb')                           { "spec/routing" }
  watch('app/controllers/application_controller.rb')  { "spec/controllers" }
  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^spec/support/(.+)\.rb$})                  { 'spec' }

  watch(%r{^app/(.+)\.rb$})                           { |m| "spec/#{m[1]}_spec.rb" }
  watch(%r{^app/(.*)(\.erb|\.haml|\.slim)$})          { |m| "spec/#{m[1]}#{m[2]}_spec.rb" }
  watch(%r{^lib/(.+)\.rb$})                           { |m| "spec/lib/#{m[1]}_spec.rb" }
  watch(%r{^app/controllers/(.+)_(controller)\.rb$})  { |m| ["spec/routing/#{m[1]}_routing_spec.rb", "spec/#{m[2]}s/#{m[1]}_#{m[2]}_spec.rb", "spec/acceptance/#{m[1]}_spec.rb"] }
  watch(%r{^app/controllers/api/(.+)\.rb$})           { |m| "spec/api/#{m[1]}_spec.rb" }
end

guard :jasmine, port: 8888, server_env: "test", all_on_start: false do
  watch(%r{spec/javascripts/spec\.(js\.coffee|js|coffee)$}) { 'spec/javascripts' }
  watch(%r{spec/javascripts/.+_spec\.(js\.coffee|js|coffee)$})
  watch(%r{spec/javascripts/fixtures/.+$})
  watch(%r{app/assets/javascripts/(.+?)\.(js\.coffee|js|coffee)(?:\.\w+)*$}) { |m| "spec/javascripts/#{ m[1] }_spec.#{ m[2] }" }
end
````

**Comment by sahin** [comment]
@nathanstitt

**Comment by e2** [comment]
@sahin - could you rerun guard with the '-d' option? (your Guardfile seems fine)

Does `rake jasmine:ci` work?

Are there any errors in your `log/test.log` file?

**Comment by fifigyuri** [comment]
The issue I reported is fixed for me.. no `decode JSON` issue any more. Thank you.

**Comment by nathanstitt** [comment]
@shahin:  I looked over the Guardfile, it looks correct.  I then attempted to locate the "An error occurred in the Jasmine runner" message in the code base and it's only used when the "guard-jasmine" command line is used.  If that's the case, then the Guardfile doesn't come into play at all.

I've just pushed up a tiny code change to include more details about the error that's occurring.  If you could, please change your Gemfile to include Guard Jasmine from the latest git source.  The line should look like:

```ruby
gem 'guard-jasmine', github: 'guard/guard-jasmine'
```

After doing so, run `gem update guard-jasmine` and then run the program under bundler, i.e. as: `bundle exec guard-jasmine`  You can verify that you're using the updated code by running `bundle exec guard-jasmine -v` which should display "2.0.3b"

I'm pretty sure you'll still receive an error, but it will hopefully provide enough details now so we can figure out if it's occurring inside guard-jasmine or perhaps in your spec's code.

I'm going to close this issue for right now since it's not related to the error you're receiving.  Please open a new issue with the contents of the updated error message and we'll figure it out.

**Comment by sahin** [comment]
I updated the gem with guard-jasmine.
it shows  
bundle exec guard-jasmine -v
Guard::Jasmine version 2.0.3b

now when I run I am getting.

Guard::Jasmine starts Jasmine Gem test server on port 57881.
Timeout while waiting for the server to startup
Most likely there is a configuration error that's preventing the server from starting
You may need to increase the `:server_timeout` option.
The commandline that was used to start the server was:
ruby -S rake jasmine JASMINE_PORT=57881
You should attempt to run that and see if any errors occur
Waiting for Jasmine test runner at http://localhost:57881/jasmine
Jasmine test runner isn't available: Connection refused - connect(2) for "localhost" port 57881
Guard::Jasmine stops server.

**Comment by sahin** [comment]
when I run like this

 ruby -S rake jasmine JASMINE_PORT=8888 RAILS_ENV=test

I can see the jasmine test page.
