### ISSUE TITLE
Cannot find tag for version 2.0.2

### ISSUE THREAD

**Issue by jhilden** [guard/guard-jasmine#183]
I have version 2.0.2 from rubygems installed, but I can't find a tag or release here in the Github repository.  Am I missing anything?

**Comment by nathanstitt** [comment]
Ah.. crap.  I missed tagging the release.  There is a commit message for it, and I'll tag it asap here

**Comment by nathanstitt** [comment]
No wait.. It's tagged.  Sorry for the confusion on my part.  If you view the tags, there's a 2.0.2

Or am I missing something?

**Comment by jhilden** [comment]
Now I can see it.  Thanks a lot.

However, I could swear it wasn't there before.  Maybe you created the tag but hadn't pushed it yet.

**Comment by e2** [comment]
@jhilden - I just tagged it and got side-tracked. Sorry guys.

@nathanstitt - you're not using `rake release` ? A lot of versions on Rubygems (since 1.9.4) aren't tagged.

**Comment by nathanstitt** [comment]
Yeah maybe.  I also note that I mucked up the last commit message where I said it was in prep for 3.0.3b, should be 2.0.3b.  Don't get your hopes up on a version 3 quite yet :)

**Comment by jhilden** [comment]
:+1: for using `rake release`

**Comment by nathanstitt** [comment]
@ec2.  Yeah I should be doing that.  I will do so in the future, thanks for the poke on it

**Comment by e2** [comment]
@nathanstitt - I usually do the following (on other projects):
1. create a draft in GH
2. bump version on master + commit locally
4. rake release:full # with octokit
5. I say 'y' to release on rubygems + accept publishing the draft on GH
6. Profit ...

**Comment by e2** [comment]
@nathanstitt , lol it's @e2 (I guess people using Amazon AWS/EC2 are going to get that wrong consistently)

**Comment by nathanstitt** [comment]
Grr.  Yeah, I was actually just running some provisioning scripts for ec2 so that was probably where my brain was.

Thanks for the tips - I haven't used octokit as yet, I'll have to check it out

**Comment by e2** [comment]
@nathanstitt - you can just rip the code from guard's `Rakefile` - I probably refactored it there a bit.

**Comment by e2** [comment]
@nathanstitt - I pushed the missing tags (2.0.0 and 2.0.1). I thought the remaining 1.19.* were missing, but I didn't see them (git tag -l doesn't sort numerically).
