### ISSUE TITLE
Error with PhantomJS 2.0

### ISSUE THREAD

**Issue by i2amsam** [guard/guard-jasmine#185]
I'm seeing an error with the latest guard-jasmine running with PhantomJS 2.0 

I see
```
TypeError: undefined is not an object (evaluating 'phantom.args[0]')
```

I believe the error is in `guard-jasmine.js` here https://github.com/guard/guard-jasmine/blob/master/lib/guard/jasmine/phantomjs/guard-jasmine.js#L5

because Phantom may have changed their API to use system instead?

http://phantomjs.org/api/phantom/property/args.html
http://phantomjs.org/api/system/property/args.html

(and also note that the system args are all incremented by 1 since `system.args[0]` is the name of the executing script now)

**Comment by nathanstitt** [comment]
Interesting catch.  I believe you're probably correct.  I'm working on a new version with additional debugging for #184 .  I'll switch to using `system.args` as outlined in your link to the Phantom docs.

Hope to have that out shortly

**Comment by nathanstitt** [comment]
Hi @i2amsam,
Thanks for letting me know about the issue with Phantomjs 2.
I've just released a new version 2.0.3, which I used the system.args with.  I also upgraded my phantomjs to version 2.0 and it worked well for me.

Please give it a try and let me know how that goes.

**Comment by pallymore** [comment]
hello @nathanstitt 

is there a reason for locking `tilt` to be >= 2.0 in version 2.0.3? it's conflicting with many of the other gems I'm using in my app. Are you using anything that specifically requires `tilt` 2.0?

Thanks,

**Comment by nathanstitt** [comment]
Nope, not at all.  I just locked it there since that's what I'd tested with and because ruby gems complained about missing versioning for it.  It's only used by the coverage tool to generate a template so the use is pretty basic.

I'll revert the locking shortly

**Comment by pallymore** [comment]
That'd be great :)

**Comment by villuorav** [comment]
I'm having trouble with the same line.
in Guardfile I have
```
guard :jasmine, debug: true do
  watch(%r{(spec/javascripts|app/assets/javascripts)}) do
    'spec/javascripts'
  end
end
```
this resulted the following request line
```
/usr/local/bin/phantomjs /Users/villu/.rvm/gems/ruby-2.2.0/gems/guard-jasmine-2.0.4/lib/guard/jasmine/phantomjs/guard-jasmine.js "http://localhost:8888/" 60000 failure true failure failure false true ''
```
which hangs -> so I ran it directly and got

```
TypeError: 'undefined' is not an object (evaluating 'system.args.args[1]')

  /Users/villu/.rvm/gems/ruby-2.2.0/gems/guard-jasmine-2.0.4/lib/guard/jasmine/phantomjs/guard-jasmine.js:7
  /Users/villu/.rvm/gems/ruby-2.2.0/gems/guard-jasmine-2.0.4/lib/guard/jasmine/phantomjs/guard-jasmine.js:147
```





I had to change the position of args, to match them to mine 
```
options = {
    url: system.args[1] || 'http://localhost:3000/jasmine',
    timeout: parseInt(system.args[2] || 10000)
};
```
What am I doing wrong?

**Comment by nathanstitt** [comment]
Thanks so much for pointing that out.  You're not doing anything wrong,  I've managed to mess up that line and it should be just `system.args`, not the `system.args.args`.  

I'm confused as to why all the specs pass with the incorrect line though and am investigating that now.  I probably need to add additional coverage to test that portion of the code

I'll be cutting a new release later today, stand by.

**Comment by pallymore** [comment]
Awesome, v2.0.5 works perfectly for me now :) Thanks!

**Comment by nathanstitt** [comment]
Pruning old issues and looks like this one didn't get closed.  Sorry for the *long* delay :)
