### ISSUE TITLE
Little bit misleading docs for the notifications

### ISSUE THREAD

**Issue by FruityFree** [guard/guard-jasmine#189]
Hi. 
I've tried to disable system notification with `notifications: false` option, as it stated in readme, but it doesn't work. 

I've looked at default options in lib/guard/jasmine.rb and it seems it should be in singular form, `notification: false` (worked for me this way)

**Comment by nathanstitt** [comment]
Thanks very much for reporting @FruityFree. I think that's always been incorrect and no-one's noticed (until now).
