### ISSUE TITLE
test environment

### ISSUE THREAD

**Issue by leviwilson** [guard/guard-jasmine#190]
I'm new to rails and I'm trying to get my project setup. I have all of my specs running from guard, so I wanted to additionally include my JS specs in there as well (so I found this gem).

The issue that I'm running into is that both by running `guard` or if I run my default rake task (which runs `jasmine:ci`) they _both_ seem to load the `:development` environment vs. the `:test` environment.

My default task looks like this:

```
task default: %i(bower:install spec jasmine:ci)
```

the `:spec` task is running with the `test` environment, so I'm unsure why I can't seem to get jasmine to do the same. Any help would be greatly appreciated.

**Comment by nathanstitt** [comment]
Hi @leviwilson, the environment of the guard task can be set by the `server_env` configuration. Something like:
```ruby
guard 'jasmine', server_env: 'test' do
  watch(%r{spec/javascripts/spec\.(js\.coffee|js|coffee)$})         { "spec/javascripts" }
end
```

I'm not sure about the `jasmine:ci` task though.  That's part of the jasmine gem, you'll have to ask them about that :)

Note that for guard-jasmine, the server env doesn't matter very much, unless you are doing `erb` interpolation in your assets that need it.  Guard Jasmine only needs to load the JS.

**Comment by leviwilson** [comment]
Thanks, I'll check out `jasmine:ci` then :+1:
