### ISSUE TITLE
Getting coverage without Rails

### ISSUE THREAD

**Issue by pezholio** [guard/guard-jasmine#191]
I have a [Sinatra project](https://github.com/TheODI-UD2D/sir_handel) with some JS specs, and we'd like to get some coverage data, which we're hoping then to push to [Coveralls](https://coveralls.io/) to get total coverage for our project (with Ruby and JS included). After much searching, it seemed that `guard-jasmine` would do the job. I'm currently running the Thor CLI command like so:

```
be guard-jasmine --coverage --coverage-html --coverage-summary --coverage-html-dir=./coverage --port=8888 --url=http://localhost:8888/
```

And the tests run as expected. However, I don't see any coverage getting generated. I've tried to dig into the code, but I'm struggling to see where in the pipeline Istanbul actually gets run. Am I missing something?

I'm pretty new to testing Javascript, but I want to do this right. Please be gentle! :)

**Comment by nathanstitt** [comment]
Sorry for the very late reply on this, @pezholio - I've updated guard jasmine to use jasmine 3.x now which may help you.

Please re-open the issue if it's still not working
