### ISSUE TITLE
Cannot run grunt alongside app server

### ISSUE THREAD

**Issue by CJBrew** [guard/guard-jasmine#198]
I've installed grunt-jasmine following the README. My (existing) Jasmine tests are running in grunt, as well as my rspec tests. 

It appears the application server and the server that's launched for Jasmine are mutually exclusive. I imagine this could be because they're both accessing the same assets or database, but I would have expected this to work out of the box.
- If I'm running `rails s` and start `grunt`, the rails server is stopped but cannot reboot because of an existing process lock (`server.pid`).

```
... WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Rendered layouts/_navbar.html.slim (13.8ms)
  Rendered layouts/_flash.html.slim (3.1ms)
Completed 200 OK in 95ms (Views: 93.4ms | ActiveRecord: 0.2ms)


* Restarting...
=> Booting Puma
=> Rails 5.0.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
A server is already running. Check /home/---/Dev/---/tmp/pids/server.pid.
Exiting
```
- If I'm running `grunt`, and start `rails s`, grunt subsequently cannot run the Jasmine tests:

```
[1] guard(main)> 
23:53:01 - INFO - Run all
23:53:01 - INFO - Running all specs
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}
..........................................................................................

Finished in 1.05 seconds (files took 2.05 seconds to load)
90 examples, 0 failures


23:53:05 - INFO - Run all Jasmine suites
23:53:05 - ERROR - An error occurred: Unable to access Jasmine specs at http://localhost:8888/. Connection refused
```

If it makes a difference, I'm using Rails 5.0.0.1.  If anyone needs Gemfiles etc., I'll build a minimal example project. 

This is apparently the same issue as I also posted here this evening:
https://github.com/jasmine/jasmine-gem/issues/272

**Comment by nathanstitt** [comment]
Hi @CJBrew, 

Thanks for the report, but I think you may have opened it on the wrong repository.  This is __Guard__-Jasmine,  not __Grunt__.  Maybe you're looking for:  https://github.com/gruntjs/grunt-contrib-jasmine ?

**Comment by CJBrew** [comment]
Ah, sorry. Yes, my mistake.

BUT the symptom is the same. Guard Jasmine also kills my app server! :)

**Comment by nathanstitt** [comment]
You may be able to work around that by setting the server port config on Guard Jasmine, please re-open if that doesn't help
